broker: broker.hivemq.com
  host: localhost
  port: 1883
bridge:
  mqtt2ros:
    - mqtt_topic: ika_acdc_22/objectList_a
      ros_topic: /topicA
    - mqtt_topic: ika_acdc_22/objectList_b
      ros_topic: /topicB
    
